# Key - Value  pliik p?aski z rozszerzeniem properti
# Rozszerzenie YAML!
spring:
  h2:
    console:
      enabled: true
      path: '/console'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: 'jdbc:h2:file:C:\Users\pawel\OneDrive\Desktop\demo\demo\db-api'
  jpa:
    hibernate:
      ddl-auto: create-drop
